import streamlit as st
import pandas as pd
import os

# Page Configuration
st.set_page_config(page_title="Retro Arcade Analytics", layout="wide")

st.markdown("""
    <h1 style='text-align: center; color: #FF007F; font-family: monospace;'>SCALA NEON ARCADE</h1>
    <h3 style='text-align: center; color: #00F0FF; font-family: monospace;'>High-Score & Telemetry Dashboard</h3>
    <hr style="border: 1px solid #00F0FF;">
""", unsafe_allow_html=True)

csv_path = os.path.join("..", "data", "telemetry.csv")

if os.path.exists(csv_path):
    # Load data generated by Scala
    df = pd.read_csv(csv_path)
    
    # --- SIDEBAR FILTERS ---
    st.sidebar.markdown("<h2 style='color: #FF007F;'>Cabinet Control</h2>", unsafe_allow_html=True)
    selected_game = st.sidebar.selectbox("Select Game Cabinet:", ["All Games"] + list(df["Game"].unique()))
    selected_tier = st.sidebar.multiselect("Filter Skill Tier:", df["SkillTier"].unique(), default=list(df["SkillTier"].unique()))
    
    # Filter dataset
    filtered_df = df[df["SkillTier"].isin(selected_tier)]
    if selected_game != "All Games":
        filtered_df = filtered_df[filtered_df["Game"] == selected_game]
        
    # --- KPI METRICS ---
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric(label="Total Sessions Logged", value=f"{len(filtered_df):,}")
    with col2:
        st.metric(label="All-Time High Score", value=f"{filtered_df['Score'].max():,}")
    with col3:
        avg_time = round(filtered_df['PlayTimeMinutes'].mean(), 1)
        st.metric(label="Average Session Length", value=f"{avg_time} Mins")

    st.markdown("---")

    # --- LEADERBOARD & CHARTS ---
    left_col, right_col = st.columns([1, 1])
    
    with left_col:
        st.subheader("Global Leaderboard Top 10")
        top_10 = filtered_df.sort_values(by="Score", ascending=False).head(10)[["Player", "Game", "Score", "SkillTier"]]
        st.dataframe(top_10.reset_index(drop=True), use_container_width=True)
        
    with right_col:
        st.subheader("Skill Tier Distribution")
        tier_counts = filtered_df["SkillTier"].value_counts()
        st.bar_chart(tier_counts, color="#FF007F")

    # --- PLAYER LOOKUP ---
    st.markdown("---")
    st.subheader("Player Profile Lookup")
    player_choice = st.selectbox("Select a Player to view history:", df["Player"].unique())
    player_df = df[df["Player"] == player_choice]
    
    st.write(f"Displaying history for gamer: {player_choice}")
    st.dataframe(player_df[["Game", "Score", "Accuracy", "PlayTimeMinutes", "SkillTier"]].reset_index(drop=True))

else:
    st.error("Error: Arcade database offline. data/telemetry.csv not found.")
    st.info("Please run the Scala generator inside the generator/ folder to populate the data directory.")

    # This automatically calculates the correct path relative to this app.py file
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
csv_path = os.path.join(BASE_DIR, "data", "telemetry.csv")